---
title: "NFL Week 2"
author: "Srikar Durgam"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)
library(patchwork) 
library(hrbrthemes)
library(ggrepel)
library(ggimage)
library(teamcolors)
if (!requireNamespace("remotes", quietly = TRUE)) {install.packages("remotes")}
remotes::install_github("mrcaseb/nflfastR")
options(scipen = 9999)
```




```{r}
data <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds'))
```

```{r}
Week3ATL <- data %>% 
            filter(week == 3) %>%
            filter(home_team == 'ATL')
```

```{r}
nfl_teamcolors <- teamcolors %>% filter(league == "nfl")
atl_color <- nfl_teamcolors %>%
  filter(name == "Atlanta Falcons") %>%
  pull(primary)
chi_color <- nfl_teamcolors %>%
  filter(name == "Chicago Bears") %>%
  pull(primary)
```

```{r, , fig.cap='A fancy pie chart.', tidy=FALSE}
Week3ATL %>% filter(!is.na(home_wp),
         !is.na(away_wp)) %>%
  dplyr::select(game_seconds_remaining,
                home_wp,
                away_wp) %>%
  gather(team, wpa, -game_seconds_remaining) %>%
  ggplot(aes(x = game_seconds_remaining, y = wpa, color = team)) +
  geom_line(size = 2) +
  geom_hline(yintercept = 0.5, color = "gray", linetype = "dashed") +
  scale_color_manual(labels = c("CHI", "ATL"),
                     values = c(chi_color, atl_color),
                     guide = FALSE) +
  scale_x_reverse(breaks = seq(0, 3600, 300)) + 
  annotate("text", x = 3000, y = .75, label = "ATL", color = atl_color, size = 8) + 
  annotate("text", x = 3000, y = .25, label = "CHI", color = chi_color, size = 8) +
  geom_vline(xintercept = 900, linetype = "dashed") + 
  geom_vline(xintercept = 1800, linetype = "dashed") + 
  geom_vline(xintercept = 2700, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") + 
  labs(
    x = "Time Remaining (seconds)",
    y = "Win Probability",
    title = "Week 3 Win Probability Chart",
    subtitle = "Chicago Bears vs Atlanta Falcons",
    caption = "Data from nflfastR"
  ) + theme_bw()

```




























